data = {
    "hi": "Hi there! I'm a friendly chatbot here to assist you.",
    "hello": "Hello! How can I help you today?",
    "what is your name": "I'm just a chatbot, so I don't have a name, but you can call me ChatBot.",
    "where are you from": "I'm from the digital world, always ready to chat!",
    "how are you": "I'm just a chatbot, but I'm here to assist you.",
    "do you have any hobbies or interests?": "I'm always busy helping users, so my hobby is chatting with people like you!",
    "what did you eat today?": "I don't eat, but I can help you find delicious recipes and food-related information.",
    "what's your favorite color?": "I'm a chatbot, so I don't have personal preferences for colors.",
    "do you enjoy listening to music?": "I can't listen to music, but I'm here to chat about it!",
    "bye": "Bye! Take care and have a great day!",
    "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
    "what's the weather like today?": "I'm sorry, I don't have access to real-time weather data.",
    "can you help me with math?": "Sure! I can assist with basic math problems.",
    "what languages do you speak?": "I speak only one language, which is the language of binary digits!",
    "what is the meaning of life?": "The answer to the ultimate question of life, the universe, and everything is 42.",
    "do you dream?": "I don't sleep, so I don't dream either!",
    "are you a robot?": "Yes, I am a chatbot, essentially a software program designed to simulate conversation.",
    "tell me something interesting": "Did you know that honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible!",
    "what's your favorite book?": "I don't read books, but I can recommend some based on popular choices!",
    "do you know any riddles?": "Sure! Here's one: I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I? Answer: An echo.",
    "who created you?": "I was created by developers at OpenAI using advanced natural language processing techniques.",
    "tell me about artificial intelligence": "Artificial intelligence (AI) is the simulation of human intelligence in machines that are programmed to think and learn like humans.",
    "what's your favorite movie?": "As a chatbot, I don't watch movies, but I can discuss popular movies with you!",
    "how old are you?": "I'm just a program, so I don't have an age in the traditional sense.",
    "do you believe in aliens?": "I don't have beliefs, but the existence of aliens is a topic of scientific inquiry and speculation.",
    "what's the capital of France?": "The capital of France is Paris.",
    "tell me about your creators": "My creators are talented developers who designed me to assist users like you!",
    "what's the largest planet in our solar system?": "Jupiter is the largest planet in our solar system.",
    "what's your favorite sport?": "I'm a chatbot, so I don't have personal preferences, but I can discuss various sports with you!",
    "how do I learn programming?": "Learning programming involves practice, patience, and using resources like online tutorials and courses.",
    "what's the speed of light?": "The speed of light in a vacuum is approximately 299,792 kilometers per second.",
    "tell me a fun fact": "A group of flamingos is called a flamboyance!",
    "what's the tallest mountain in the world?": "Mount Everest is the tallest mountain above sea level, standing at 8,848 meters (29,029 feet).",
    "can you play chess?": "I don't have the capability to play chess, but I can provide information about the game.",
    "what's the difference between AI and machine learning?": "AI is the broader concept of machines being able to carry out tasks in a way that we would consider 'smart'. Machine learning is a subset of AI where machines are trained to learn from data and improve over time.",
    "tell me a proverb": "A stitch in time saves nine.",
    "what's the longest river in the world?": "The Nile River in Africa is considered the longest river in the world.",
    "what's your favorite food?": "I don't eat, but I can help you find recipes for various dishes!",
    "do you know any tongue twisters?": "Sure! Try saying 'She sells seashells by the seashore' five times fast!",
    "how do airplanes fly?": "Airplanes fly using the principles of aerodynamics, generating lift with their wings as they move through the air.",
    "what's the capital of Japan?": "The capital of Japan is Tokyo.",
    "tell me about Elon Musk": "Elon Musk is a business magnate, industrial designer, and engineer. He is known for founding Tesla, SpaceX, and other ventures.",
    "what's the largest ocean in the world?": "The Pacific Ocean is the largest ocean by both area and volume.",
    "what's your favorite animal?": "I'm a chatbot, so I don't have personal preferences, but I can tell you interesting facts about animals!",
    "tell me a science fact": "In 1928, Alexander Fleming discovered penicillin, the first natural antibiotic.",
    "what's the tallest building in the world?": "As of now, the tallest building in the world is the Burj Khalifa in Dubai, United Arab Emirates.",
    "what's the smallest country in the world?": "The smallest country in the world by land area is Vatican City.",
    "what's your favorite video game?": "I'm a chatbot, so I don't play video games, but I can discuss popular video games with you!",
    "tell me about climate change": "Climate change refers to significant changes in global temperatures and weather patterns over time, primarily due to human activities.",
    "what's the coldest place on Earth?": "The coldest place on Earth is Antarctica, where temperatures can drop below -80 degrees Celsius (-112 degrees Fahrenheit).",
    "how do plants make food?": "Plants make food through a process called photosynthesis, using sunlight, water, and carbon dioxide to produce glucose and oxygen.",
    "tell me about Albert Einstein": "Albert Einstein was a theoretical physicist who developed the theory of relativity, one of the two pillars of modern physics.",
    "what's the largest desert in the world?": "The largest desert in the world is the Antarctic Desert.",
    "what's your favorite holiday?": "As a chatbot, I don't have personal preferences, but I can provide information about various holidays celebrated around the world!",
    "tell me about the Great Wall of China": "The Great Wall of China is a series of fortifications made of stone, brick, tamped earth, wood, and other materials, built along the northern borders of China to protect against invasions.",
    "do you know any famous quotes?": "Sure! 'The only way to do great work is to love what you do.' – Steve Jobs",
    "what's the largest mammal in the world?": "The blue whale is the largest mammal in the world.",
    "what's the circumference of the Earth?": "The equatorial circumference of the Earth is approximately 40,075 kilometers (24,901 miles).",
    "tell me about Marie Curie": "Marie Curie was a physicist and chemist who conducted pioneering research on radioactivity. She was the first woman to win a Nobel Prize and remains the only person to win Nobel Prizes in two different sciences (Physics and Chemistry).",
    "what's the pH scale?": "The pH scale measures how acidic or basic a substance is, ranging from 0 (most acidic) to 14 (most basic), with 7 being neutral.",
    "what's the largest waterfall in the world?": "Angel Falls in Venezuela is the highest uninterrupted waterfall in the world, with a total drop of 979 meters (3,212 feet).",
    "tell me about the history of computers": "Computers have evolved significantly since their invention. The first modern digital computer was developed in the mid-20th century, and since then, computing power and capabilities have grown exponentially.",
    "what's the difference between a virus and bacteria?": "Viruses are smaller than bacteria and cannot survive or replicate without a host cell. Bacteria are single-celled organisms that can reproduce independently.",
    "what's the largest bird in the world?": "The ostrich is the largest bird in the world by height and weight.",
    "what's the deepest part of the ocean?": "The Mariana Trench in the western Pacific Ocean is the deepest part of the ocean, reaching a depth of about 36,070 feet (10,994 meters).",
    "tell me about Nelson Mandela": "Nelson Mandela was a South African anti-apartheid revolutionary, political leader, and philanthropist who served as President of South Africa from 1994 to 1999.",
    "what is OpenAI?": "OpenAI is an artificial intelligence research laboratory and deployment company. It aims to ensure that artificial general intelligence (AGI) benefits all of humanity.",
    "what is the meaning of AGI?": "AGI stands for Artificial General Intelligence, which refers to a type of artificial intelligence that is as capable as humans across a wide range of tasks.",
    "what is Python programming language?": "Python is a high-level, interpreted programming language known for its simplicity and readability. It is widely used for web development, scientific computing, data analysis, and artificial intelligence applications.",
    "what are the benefits of machine learning?": "Machine learning enables computers to learn and improve from experience without being explicitly programmed. It has applications in various fields such as healthcare, finance, and autonomous vehicles.",
    "tell me about quantum computing": "Quantum computing is a field of computing that uses principles of quantum mechanics, such as superposition and entanglement, to perform calculations. It has the potential to solve certain problems much faster than classical computers.",
    "what is blockchain?": "Blockchain is a decentralized and distributed digital ledger technology that records transactions across multiple computers. It is best known for its use in cryptocurrencies like Bitcoin.",
    "what is the future of AI?": "The future of AI holds potential advancements in areas such as autonomous systems, healthcare diagnostics, personalized education, and enhanced customer service through chatbots like me!",
    "what are the ethical concerns of AI?": "Ethical concerns surrounding AI include issues related to privacy, bias in algorithms, job displacement, and the implications of autonomous decision-making systems.",
    "tell me about the Turing test": "The Turing test, proposed by Alan Turing in 1950, is a test of a machine's ability to exhibit intelligent behavior equivalent to, or indistinguishable from, that of a human.",
    "what is machine learning?": "Machine learning is a subset of artificial intelligence that focuses on the development of algorithms that allow computers to learn and make decisions from data. It enables systems to automatically learn and improve from experience without being explicitly programmed.",
    "what is natural language processing (NLP)?": "Natural Language Processing (NLP) is a field of artificial intelligence focused on enabling computers to understand, interpret, and generate human language.",
    "what is reinforcement learning?": "Reinforcement learning is a type of machine learning where an agent learns to make decisions in an environment by performing actions and receiving rewards or penalties.",
    "what is deep learning?": "Deep learning is a subset of machine learning that uses neural networks with many layers (hence 'deep') to learn patterns from data. It has achieved remarkable success in tasks such as image and speech recognition.",
    "what are neural networks?": "Neural networks are computing systems inspired by the human brain's neural structure. They consist of interconnected nodes, or neurons, that process and transmit information.",
    "what is the difference between AI and human intelligence?": "AI refers to machines simulating human cognitive functions like learning and problem-solving. Human intelligence encompasses a broader range of abilities, including emotional and social intelligence.",
    "how does facial recognition work?": "Facial recognition uses algorithms to identify and verify individuals based on facial features extracted from images or video footage.",
    "what is the Singularity?": "The Singularity refers to a hypothetical future point in time when artificial intelligence will surpass human intelligence, leading to unpredictable changes in society.",
    "what is cloud computing?": "Cloud computing refers to the delivery of computing services, including servers, storage, databases, networking, software, over the internet ('the cloud'). It enables organizations to scale resources and access technology without investing in physical infrastructure.",
    "what is augmented reality (AR)?": "Augmented Reality (AR) is a technology that superimposes digital information, such as images, sounds, and text, onto the real-world environment, typically viewed through a device like a smartphone or AR glasses.",
    "what is virtual reality (VR)?": "Virtual Reality (VR) is a computer-generated simulation of a three-dimensional environment that users can interact with using specialized equipment, such as VR headsets.",
    "what is the Internet of Things (IoT)?": "The Internet of Things (IoT) refers to a network of interconnected devices embedded with sensors, software, and other technologies that enable them to collect and exchange data over the internet.",
    "what are chatbots?": "Chatbots are computer programs designed to simulate conversation with human users, typically through messaging applications, websites, or virtual assistants.",
    "what is the difference between AI and robotics?": "AI focuses on developing systems capable of performing tasks that would typically require human intelligence. Robotics involves designing and building physical machines, or robots, to perform specific tasks or functions.",
    "what is supervised learning?": "Supervised learning is a type of machine learning where the model is trained on labeled data, with input-output pairs provided to the algorithm during training. The goal is to learn a mapping from inputs to outputs.",
    "what is unsupervised learning?": "Unsupervised learning is a type of machine learning where the model is trained on unlabeled data, and the algorithm tries to learn patterns or relationships from the data without specific output labels.",
    "what is semi-supervised learning?": "Semi-supervised learning is a type of machine learning where the model is trained on a combination of labeled and unlabeled data. It leverages both labeled data with known outcomes and unlabeled data to improve learning accuracy.",
    "what is transfer learning?": "Transfer learning is a machine learning technique where a model trained on one task is reused or adapted as a starting point for a different but related task. It helps to leverage existing knowledge and improve learning efficiency.",
    "what is generative adversarial networks (GANs)?": "Generative Adversarial Networks (GANs) are a type of deep learning model where two neural networks, the generator and the discriminator, compete against each other. The generator creates new data instances, while the discriminator evaluates them for authenticity.",
    "what is computer vision?": "Computer vision is a field of artificial intelligence that enables computers to interpret and understand visual information from the real world, such as images and videos.",
    "what is autonomous driving?": "Autonomous driving, also known as self-driving or driverless cars, refers to vehicles capable of navigating and operating without human input or intervention. It relies on sensors, cameras, radar, and artificial intelligence to perceive and navigate the environment.",
    "what is NLP used for?": "Natural Language Processing (NLP) is used for tasks such as language translation, sentiment analysis, speech recognition, and text generation. It enables computers to understand and process human language.",
    "what is the difference between AI and AGI?": "AI refers to machines that can perform tasks requiring human intelligence, such as problem-solving and learning. AGI (Artificial General Intelligence) refers to AI that exhibits intelligence at a human level across a broad range of tasks and contexts.",
    "what is computer programming?": "Computer programming is the process of designing and writing instructions (code) that computers can execute to perform specific tasks or functions. It involves languages like Python, Java, and C++.",
    "what is the Turing test used for?": "The Turing test is used to assess a machine's ability to exhibit intelligent behavior indistinguishable from that of a human. It tests a machine's conversational capabilities and understanding of natural language.",
    "what is the future of robotics?": "The future of robotics holds promise for advancements in areas such as healthcare (surgical robots), manufacturing (automation), space exploration, and personal assistance (domestic robots).",
    "what is quantum supremacy?": "Quantum supremacy refers to the point at which a quantum computer can solve problems that are infeasible for classical computers to solve within a reasonable timeframe. It demonstrates the potential superiority of quantum computing over classical computing in certain applications.",
    "what is the difference between machine learning and deep learning?": "Machine learning is a subset of artificial intelligence focused on algorithms that can learn and make predictions from data. Deep learning is a subset of machine learning that uses neural networks with many layers (deep neural networks) to learn patterns from data.",
    "what is the difference between machine learning and data science?": "Machine learning is a component of data science that focuses on algorithms and statistical models to perform tasks without explicit programming. Data science encompasses a broader range of activities, including data collection, cleaning, analysis, and interpretation to extract insights and make informed decisions.",
    "what is the difference between AI and automation?": "AI refers to machines performing tasks that typically require human intelligence, such as learning, reasoning, and problem-solving. Automation refers to using technology to perform specific tasks or processes with minimal human intervention.",
    "what is the difference between artificial intelligence and machine intelligence?": "Artificial Intelligence (AI) is a broader concept of machines simulating human intelligence. Machine intelligence is a subset of AI, focusing on specific tasks or functions machines can perform based on programmed instructions and algorithms.",
    "what is the difference between robotics and automation?": "Robotics involves designing and building physical machines (robots) capable of performing tasks or functions autonomously or semi-autonomously. Automation refers to using technology to perform specific tasks or processes with minimal human intervention, which may or may not involve physical robots.",
    "what is the difference between augmented reality (AR) and virtual reality (VR)?": "Augmented Reality (AR) overlays digital information, such as images and text, onto the real-world environment, enhancing the user's perception of reality. Virtual Reality (VR) immerses users in a computer-generated simulation of a three-dimensional environment, typically viewed through VR headsets or devices.",
    "what is the difference between deep learning and machine learning?": "Deep learning is a subset of machine learning that uses neural networks with multiple layers (deep neural networks) to learn patterns from data. Machine learning encompasses a broader range of algorithms and statistical models that enable machines to learn from and make predictions or decisions based on data.",
    "what is the difference between NLP and text mining?": "Natural Language Processing (NLP) focuses on enabling computers to understand, interpret, and generate human language. Text mining involves extracting useful information and insights from large volumes of textual data, often using techniques from natural language processing, machine learning, and statistical analysis.",
    "what is the difference between supervised learning and unsupervised learning?": "Supervised learning is a type of machine learning where the model is trained on labeled data, with input-output pairs provided during training. Unsupervised learning is a type of machine learning where the model is trained on unlabeled data, and the algorithm tries to learn patterns or relationships from the data without specific output labels.",
    "what is the difference between AI and AGI?": "AI refers to machines that can perform tasks requiring human intelligence, such as problem-solving and learning. AGI (Artificial General Intelligence) refers to AI that exhibits intelligence at a human level across a broad range of tasks and contexts."
}

def get_response(user_input):
    for pattern, response in data.items():
        if pattern in user_input:
            return response
    return "I'm sorry, I didn't understand that. Can you please rephrase your sentence?"
